apiVersion: v1
kind: Namespace
metadata:
  name: dfr-console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfr-console
  namespace: dfr-console
  labels:
    app: dfr-console
    app.kubernetes.io/component: dfr-console
    app.kubernetes.io/instance: dfr-console
    app.kubernetes.io/part-of: dfr-console
    app.openshift.io/runtime-namespace: dfr-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfr-console
  template:
    metadata:
      labels:
        app: dfr-console
    spec:
      containers:
        - name: dfr-console
          image: quay.io/vszocs/dfr-console
          ports:
            - containerPort: 9002
              protocol: TCP
          imagePullPolicy: Always
          args:
            - '--ssl'
            - '--cert=/var/serving-cert/tls.crt'
            - '--key=/var/serving-cert/tls.key'
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: dfr-console
  namespace: dfr-console
  labels:
    app: dfr-console
    app.kubernetes.io/component: dfr-console
    app.kubernetes.io/instance: dfr-console
    app.kubernetes.io/part-of: dfr-console
spec:
  ports:
    - name: 9002-tcp
      protocol: TCP
      port: 9002
      targetPort: 9002
  selector:
    app: dfr-console
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: dfr-console
spec:
  displayName: 'Data Federation Plugin'
  service:
    name: dfr-console
    namespace: dfr-console
    port: 9002
    basePath: '/'
